import Head from "next/head";
import Landing from "../components/home/Landing";
import Navbar from "../components/layout/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello and welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Landing />
    </>
  );
}
